name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t simple-flask-app .

    - name: Run Tests
      run: |
        docker run --rm simple-flask-app python -m unittest discover -s tests -p '*_test.py'

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.akshay1669 }}
        password: ${{ secrets.Akshay@1234 }}

    - name: Push Docker Image
      run: |
        docker tag simple-flask-app ${{ secrets.akshay1669 }}/simple-flask-app:latest
        docker push ${{ secrets.akshay1669 }}/simple-flask-app:latest
